# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53f71a40888304e41a847fddc197f71f70607e7978e5ca8a826844d901176918feaf6c1dfb81d1eaa8830d137b6db7c9ed84e7f0483efcd31dad353b78a01a13

test:
  secret_key_base: 5a17df1d00b438640e83772608acec6c8820766179e03bb3adab129b30bbd4116eee8805901fbab332a25d9b50a9fe515248aac631ed6f6d9fd340397586882b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
